export const PERMISSIONS = {
  VIEW_ASSETS: 'VIEW_ASSETS',
  MANAGE_ASSETS: 'MANAGE_ASSETS',
  ALLOCATE_ASSETS: 'ALLOCATE_ASSETS',
  BOOK_ASSETS: 'BOOK_ASSETS',
  MANAGE_MAINTENANCE: 'MANAGE_MAINTENANCE',
  PERFORM_AUDIT: 'PERFORM_AUDIT',
  VIEW_REPORTS: 'VIEW_REPORTS'
};

export default PERMISSIONS;
